### ISSUE TITLE
TODO: Station marks

### ISSUE THREAD

**Issue by a-random-lemurian** [a-random-lemurian/opengeofiction-americana#2]
![image](https://github.com/a-random-lemurian/opengeofiction-americana/assets/74448738/37c91aad-fb18-4e6e-a538-f31e2103fb4c)
Google Maps has station marks, perhaps Americana could, too?

TODO:
- [ ] Figure out how station marks should be tagged
- [ ] Find out how to include them in the vector tiles
- [ ] Find out how to host the icons
